stages:
  - nix-build
  - stack-build

variables:
    STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"

nix-build:
  stage: nix-build
  image: nixos/nix:latest
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - /nix/store/
  script:
    - nix-env -i git
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - nix-build 
stack-build:
  stage: stack-build
  image: fpco/stack-build:lts-13.11
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .stack-work/
      - .stack-root/
  script:
    - stack --no-nix --no-terminal build
