name: gitchapter
version: '0.1.0.0'
author: Chris Stryczynski
maintainer: Chris Stryczynski
license: BSD3
dependencies:
- base >=4.9 && <4.15
- turtle
- text
- safe
- unix
- foldl
- string-conversions
- filepath
- system-filepath
- parsec
- mtl
- directory
- regex-posix
- regex-pcre
- optparse-applicative
- extra
- transformers
- QuickCheck
- HUnit
- pretty-simple
- process 
- template-haskell
- pretty-simple
- pandoc-include-code
- unordered-containers
- rainbow

executables:
  gitchapter:
    main: Main.hs
    source-dirs: src
  test:
    main: Test.hs
    ghc-options: -main-is Test
    source-dirs: src
